name: tfsec-commentor
on: [push, pull_request]
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ github.token }}
          
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v2.2.1
        with:
          tfsec_output_format: JSON
